[package]
name = "rage-fivem-file-checker"
version = "1.0.0"
description = "Read-only scanner for FiveM installation files and folders"
authors = ["ALTAF"]
edition = "2021"

[lib]
name = "fivem_file_checker_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
